In [2]:
import numpy as np
from scipy import stats

In [3]:
x = np.zeros((3,3,5))
y = np.zeros_like(x)
means1 = np.array([10,20,30])
means2 = [4,5,6]
for i in range(3):
    for j in range(3):
        x[i,j,:] = stats.norm.rvs(means1[i],0,size=5)

In [13]:
for i in range(3):
    x[i,:,:] = stats.norm.rvs(means1[i],1,size=(3,5),random_state=0)
    y[:,i,:] = stats.norm.rvs(means1[i],1,size=(3,5),random_state=0)
print(x)
print(' ................. ')
print(y)

[[[11.76405235 10.40015721 10.97873798 12.2408932  11.86755799]
  [ 9.02272212 10.95008842  9.84864279  9.89678115 10.4105985 ]
  [10.14404357 11.45427351 10.76103773 10.12167502 10.44386323]]

 [[21.76405235 20.40015721 20.97873798 22.2408932  21.86755799]
  [19.02272212 20.95008842 19.84864279 19.89678115 20.4105985 ]
  [20.14404357 21.45427351 20.76103773 20.12167502 20.44386323]]

 [[31.76405235 30.40015721 30.97873798 32.2408932  31.86755799]
  [29.02272212 30.95008842 29.84864279 29.89678115 30.4105985 ]
  [30.14404357 31.45427351 30.76103773 30.12167502 30.44386323]]]
 ................. 
[[[11 10 10 12 11]
  [21 20 20 22 21]
  [31 30 30 32 31]]

 [[ 9 10  9  9 10]
  [19 20 19 19 20]
  [29 30 29 29 30]]

 [[10 11 10 10 10]
  [20 21 20 20 20]
  [30 31 30 30 30]]]


Generate a tile of your means then use those means in the norm rvs

In [5]:
temp = np.expand_dims(means1,axis=1)
temp = np.tile(temp,(5))
temp = np.expand_dims(temp,axis=1)
temp = np.tile(temp,(3,1))
x = stats.norm.rvs(temp,1,size=(3,3,5),random_state = 0)
x

array([[[11.76405235, 10.40015721, 10.97873798, 12.2408932 ,
         11.86755799],
        [ 9.02272212, 10.95008842,  9.84864279,  9.89678115,
         10.4105985 ],
        [10.14404357, 11.45427351, 10.76103773, 10.12167502,
         10.44386323]],

       [[20.33367433, 21.49407907, 19.79484174, 20.3130677 ,
         19.14590426],
        [17.44701018, 20.6536186 , 20.8644362 , 19.25783498,
         22.26975462],
        [18.54563433, 20.04575852, 19.81281615, 21.53277921,
         21.46935877]],

       [[30.15494743, 30.37816252, 29.11221425, 28.01920353,
         29.65208785],
        [30.15634897, 31.23029068, 31.20237985, 29.61267318,
         29.69769725],
        [28.95144703, 28.57998206, 28.29372981, 31.9507754 ,
         29.49034782]]])

In [8]:
x.shape

(3, 3, 5)

In [6]:
help(stats.norm.rvs)

Help on method rvs in module scipy.stats._distn_infrastructure:

rvs(*args, **kwds) method of scipy.stats._continuous_distns.norm_gen instance
    Random variates of given type.
    
    Parameters
    ----------
    arg1, arg2, arg3,... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information).
    loc : array_like, optional
        Location parameter (default=0).
    scale : array_like, optional
        Scale parameter (default=1).
    size : int or tuple of ints, optional
        Defining number of random variates (default is 1).
    random_state : {None, int, `numpy.random.Generator`,
                    `numpy.random.RandomState`}, optional
    
        If `seed` is None (or `np.random`), the `numpy.random.RandomState`
        singleton is used.
        If `seed` is an int, a new ``RandomState`` instance is used,
        seeded with `seed`.
        If `seed` is already a ``Generator`` or ``RandomState`` ins