In [21]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import os
import dill
import importlib


In [22]:
import Subject_Object
importlib.reload(Subject_Object)
from Subject_Object import *

## Initial Thangs

In [23]:
os.chdir('D:\\Subject_Data\\Seth_MatchPennies_Agent_Exp1\\')
PATH = os.getcwd()
# Fields pull and pull list
os.chdir('D:\Subject_Data\Seth_MatchPennies_Agent_Exp1')
PATH = os.getcwd()
figures_pull_list = []
fields_pull = []
with open(PATH+"\\Figures_Pull_List.txt", "r") as pull_file:
    figures_pull_list = pull_file.read().splitlines()
with open(PATH+"\\Fields_Pull.txt", "r") as fields_pull:
    fields_pull = fields_pull.read().splitlines()
NUM_SUBJECTS = len(figures_pull_list)
task_name = 'Seth_MatchPennies_Agent_Exp1'

## dill Load

dill Load Control Tasks


In [24]:
coincidence_trials = 50
reaction_trials = 50
interval_trials = 50
# ---------------Controls-------------------------
player_reaction_decision_array = np.empty((NUM_SUBJECTS, reaction_trials))
agent_reaction_decision_array = np.empty((NUM_SUBJECTS, reaction_trials))
player_reaction_time = np.zeros([NUM_SUBJECTS,reaction_trials])*np.nan 
player_reaction_movement_time = np.zeros([NUM_SUBJECTS,reaction_trials])*np.nan
reaction_trial_start = np.zeros((NUM_SUBJECTS,reaction_trials))*np.nan 
coincidence_trial_start = np.zeros((NUM_SUBJECTS, coincidence_trials))*np.nan
coincidence_reach_time = np.zeros((NUM_SUBJECTS, coincidence_trials))*np.nan
interval_trial_start = np.zeros((NUM_SUBJECTS, interval_trials))*np.nan
interval_reach_time = np.zeros((NUM_SUBJECTS, interval_trials))*np.nan

for i in range(NUM_SUBJECTS):
    subname = figures_pull_list[i]
    data_path = PATH+f'\\Subjects_Analyzed\\{subname}\\'
    reaction_trial_start[i,:] = dill.load(open(data_path + f'{subname}_reaction_trial_start.pkl', 'rb'))
    player_reaction_time[i,:] = dill.load(open(data_path + f'{subname}_player_reaction_time.pkl', 'rb'))
    player_reaction_movement_time[i,:] = dill.load(open(data_path + f'{subname}_player_reaction_movement_time.pkl', 'rb'))
    player_reaction_decision_array[i,:] = dill.load(open(data_path + f'{subname}_player_reaction_decision_array.pkl', 'rb'))
    agent_reaction_decision_array[i,:] = dill.load(open(data_path + f'{subname}_agent_reaction_decision_time.pkl', 'rb'))
    reaction_trial_start[i,:] = dill.load(open(data_path + f'{subname}_reaction_trial_start.pkl', 'rb'))
    interval_trial_start[i,:] = dill.load(open(data_path + f'{subname}_interval_trial_start.pkl', 'rb'))
    interval_reach_time[i,:] = dill.load(open(data_path + f'{subname}_interval_reach_time.pkl', 'rb'))
    coincidence_trial_start[i,:] = dill.load(open(data_path + f'{subname}_coincidence_trial_start.pkl', 'rb'))
    coincidence_reach_time[i,:] =  dill.load(open(data_path + f'{subname}_coincidence_reach_time.pkl', 'rb'))
    print(subname)
    print(player_reaction_time[i])

Sub1
[570. 417. 289. 319. 315. 346. 333. 315. 356. 457. 243. 247. 258. 288.
 307. 293. 269. 306. 275. 292. 251. 319. 268. 295. 326. 261. 314. 258.
 303. 294. 275. 328. 276. 286. 264. 249. 270. 271. 257. 277. 239. 312.
 261. 255. 266. 279. 320. 301. 260. 285.]
Sub2
[497. 329. 334. 259. 300. 297. 292. 302. 299. 327. 325. 305. 338. 286.
 275. 293. 285. 344. 346. 313. 271. 315. 318. 298. 283. 300. 330. 299.
 349. 314. 338. 337. 335. 270. 294. 314. 309. 324. 308. 302. 308. 325.
 308. 284. 309. 270. 291. 350. 316. 316.]
Sub3
[387. 266. 323. 389. 351. 327. 304. 343. 309. 362. 309. 343. 272. 263.
 292. 323. 264. 328. 313. 338. 378. 346. 283. 308. 320. 294. 313. 344.
 451. 316. 325. 326. 390. 319. 410. 359. 352. 390. 293. 294. 327. 380.
 280. 290. 352. 282. 372. 353. 326. 394.]
Sub4
[520. 392. 328. 339. 390. 452. 365. 397. 346. 317. 331. 342. 351. 334.
 363. 298. 307. 377. 333. 299. 409. 411. 313. 319. 356. 331. 465. 333.
 393. 345. 307. 310. 313. 333. 336. 314. 361. 308. 321. 394. 347. 326.
 3

dill Load Task and Washout

In [25]:
path1 = PATH+'\\'+'Sub1_Task'
task_df = pd.read_csv(path1+f'\\Sub1_TaskTrial_Table.csv')
task_df = task_df.loc[task_df['Condition type']==3] # Only get the task condition 
num_trials = int(task_df.iloc[-1]['Block_Step']) # number of trials in each block
num_blocks = int(task_df.iloc[-1]['Block_Row']/2)
tot_trials = int(num_trials*num_blocks)
trial_time = int(task_df.iloc[0]['Condition time'])
task_df_columns = len(fields_pull)
trial_table = np.empty((NUM_SUBJECTS, tot_trials, 4), int)
#----------------- TASK--------------------------------
player_task_reach_time = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan 
player_task_decision_time = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan 
player_task_decision_array = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan
player_task_movement_time = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan
agent_task_reach_time = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan 
agent_task_decision_time = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan 
agent_task_decision_array = np.zeros([NUM_SUBJECTS,num_blocks,num_trials])*np.nan

# -------------- Washout-------------------
washout_trials = 25
player_washout_reach_time = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan 
player_washout_decision_time = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan 
player_washout_decision_array = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan
player_washout_movement_time = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan
agent_washout_reach_time = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan 
agent_washout_decision_time = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan 
agent_washout_decision_array = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan
agent_washout_movement_time = np.zeros([NUM_SUBJECTS,num_blocks,washout_trials])*np.nan

for i in range(NUM_SUBJECTS):
    subname = figures_pull_list[i]
    data_path = PATH+f'\\Subjects_Analyzed\\{subname}\\'
    #task_data[i,:,:,:,:] = dill.load(open(data_path + f'{subname}_task_data.pkl', 'rb'))
    player_task_decision_time[i,:,:] = dill.load( open(data_path + f'{subname}_player_task_decision_time.pkl', 'rb'))
    player_task_decision_array[i,:,:] = dill.load( open(data_path + f'{subname}_player_task_decision_array.pkl', 'rb'))
    player_task_movement_time[i,:,:] = dill.load(open(data_path + f'{subname}_player_task_movement_time.pkl', 'rb'))
    player_task_reach_time[i,:,:] = dill.load( open(data_path + f'{subname}_player_task_reach_time.pkl', 'rb'))
    agent_task_decision_time[i,:,:] = dill.load( open(data_path + f'{subname}_agent_task_decision_time.pkl', 'rb'))
    agent_task_decision_array[i,:,:] = dill.load(open(data_path + f'{subname}_agent_task_decision_array.pkl', 'rb'))
    agent_task_reach_time[i,:,:] = agent_task_decision_time[i,:,:] + 150
    player_washout_decision_time[i,:,:] = dill.load( open(data_path + f'{subname}_player_washout_decision_time.pkl', 'rb'))
    player_washout_decision_array[i,:,:] = dill.load( open(data_path + f'{subname}_player_washout_decision_array.pkl', 'rb'))
    player_washout_movement_time[i,:,:] = dill.load(open(data_path + f'{subname}_player_washout_movement_time.pkl', 'rb'))
    player_washout_reach_time[i,:,:] = dill.load( open(data_path + f'{subname}_player_washout_reach_time.pkl', 'rb'))
    agent_washout_decision_time[i,:,:] = dill.load( open(data_path + f'{subname}_agent_washout_decision_time.pkl', 'rb'))
    agent_washout_decision_array[i,:,:] = dill.load(open(data_path + f'{subname}_agent_washout_decision_array.pkl', 'rb'))
    agent_washout_reach_time[i,:,:] = dill.load(open(data_path + f'{subname}_agent_washout_reach_time.pkl', 'rb'))

## Generate Subject Objects

In [26]:
NUM_STDS = 2
append_dict = {0:'reaction_time_no_sd_off',1:'reaction_time_minus_sd',2:'reaction_time_minus_2sd'}
data_path = 'D:\\Subject_Data\\Seth_MatchPennies_Agent_Exp1\\Subjects_Analyzed\\'
subject_object_dict = {}
for i in range(NUM_SUBJECTS):
    subname = figures_pull_list[i]
    # print(subname)
    subject_object_dict.update({subname: Subject(num_trials = 80, num_blocks = 6, num_control_trials = 50, num_washout_trials = 25, reaction_time = player_reaction_time[i], reaction_movement_time = player_reaction_movement_time[i],
                                interval_trial_start = interval_trial_start[i], interval_reach_time = interval_reach_time[i], coincidence_trial_start = coincidence_trial_start[i], coincidence_reach_time = coincidence_reach_time[i],
                                player_task_reach_time = player_task_reach_time[i], player_task_decision_time = player_task_decision_time[i], player_task_decision_array = player_task_decision_array[i],
                                player_task_movement_time = player_task_movement_time[i], agent_task_reach_time = agent_task_reach_time[i], agent_task_decision_time = agent_task_decision_time[i], agent_task_decision_array = agent_task_decision_array[i],
                                player_washout_reach_time = player_washout_reach_time[i], player_washout_decision_time = player_washout_decision_time[i], player_washout_decision_array = player_washout_decision_array[i],
                                player_washout_movement_time = player_washout_movement_time[i], agent_washout_reach_time = agent_washout_reach_time[i], agent_washout_decision_time = agent_washout_decision_time[i], agent_washout_decision_array = agent_washout_decision_array[i],
                                num_stds_for_reaction_time = NUM_STDS
                                )}
                               )
    # print(player_reaction_time[i])
    dill.dump(subject_object_dict[subname], open(data_path + f'{subname}\\{subname}_object_{append_dict[NUM_STDS]}.pkl', 'wb'))
dill.dump(subject_object_dict,open(data_path + f'subject_object_{append_dict[NUM_STDS]}_dict.pkl', 'wb'))

group = Group(list(subject_object_dict.values()))
print(group.adjusted_reaction_time_mean)
dill.dump(group,open(data_path + f'group_object_{append_dict[NUM_STDS]}.pkl','wb'))

c:\Users\Seth Sullivan\OneDrive - University of Delaware - o365\Desktop\MatchPennies-Agent-Expirement\Analysis and Figures Scripts\Exp1 Scripts\Subject_Object.py:298: RuntimeWarning: invalid value encountered in divide
  # Get percentages based on bin length
c:\Users\Seth Sullivan\OneDrive - University of Delaware - o365\Desktop\MatchPennies-Agent-Expirement\Analysis and Figures Scripts\Exp1 Scripts\Subject_Object.py:299: RuntimeWarning: invalid value encountered in divide
  self.perc_binned_player_wins = (self.binned_player_wins/self.bin_length_each_condition)*100
c:\Users\Seth Sullivan\OneDrive - University of Delaware - o365\Desktop\MatchPennies-Agent-Expirement\Analysis and Figures Scripts\Exp1 Scripts\Subject_Object.py:300: RuntimeWarning: invalid value encountered in divide
  self.perc_binned_player_indecisions = (self.binned_player_indecisions/self.bin_length_each_condition)*100
c:\Users\Seth Sullivan\OneDrive - University of Delaware - o365\Desktop\MatchPennies-Agent-Expirement

(11, 6)
262.51805105390616


In [27]:
for sub in figures_pull_list:
    print(subject_object_dict[sub].player_indecisions)

[ 3. 14. 13.  4.  3. 15.]
[ 1.  7. 16. 13. 26. 18.]
[ 4.  7. 28.  8. 26.  4.]
[ 6.  9.  5. 11.  6. 16.]
[ 5. 10. 19. 16. 18.  9.]
[ 7.  6.  8. 25. 19.  5.]
[13. 27. 28. 38. 75. 36.]
[ 2.  9. 19.  7. 10.  6.]
[ 4.  9. 23. 28. 35. 27.]
[ 3. 19. 27. 18. 11. 15.]
[ 3. 19.  9. 17. 23.  6.]
[15. 17. 14. 15. 11. 17.]
[ 7.  1. 63.  3. 17.  5.]
[13. 13. 37. 15. 17. 14.]
[ 2.  8.  9.  8. 15.  6.]
[10. 22. 18. 32. 14. 16.]
[3. 3. 3. 3. 1. 3.]
[ 8. 18. 30. 20. 15. 13.]
[ 0.  5. 14.  4. 17. 17.]
