In [6]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import dill
import sys
import importlib
import os

from scipy import optimize
'''
This script fits the decision time of the model to match the data

metrics as of 2/22/23 aare just wins, indecisions,incorrects

'''

'\nThis script fits the decision time of the model to match the data\n\nmetrics as of 2/22/23 aare just wins, indecisions,incorrects\n\n'

# Initial Thangs

In [7]:
sys.path.insert(0,r'C:\Users\Seth Sullivan\OneDrive - University of Delaware - o365\Desktop\MatchPennies-Agent-Expirement\Analysis and Figures Scripts\Exp1 Scripts')
from Subject_Object import *
from plot_functions import *

import Optimal_Stopping_Object_v3
importlib.reload(Optimal_Stopping_Object_v3)

<module 'Optimal_Stopping_Object_v3' from 'c:\\Users\\Seth Sullivan\\OneDrive - University of Delaware - o365\\Desktop\\MatchPennies-Agent-Expirement\\Modeling Scripts\\Optimal Stopping\\Optimal_Stopping_Object_v3.py'>

In [8]:
os.chdir('D:\\Subject_Data\\Seth_MatchPennies_Agent_Exp1\\')
PATH = os.getcwd()
# Fields pull and pull list
os.chdir('D:\Subject_Data\Seth_MatchPennies_Agent_Exp1')
PATH = os.getcwd()
figures_pull_list = []
fields_pull = []
with open(PATH+"\\Figures_Pull_List.txt", "r") as pull_file:
    figures_pull_list = pull_file.read().splitlines()
with open(PATH+"\\Fields_Pull.txt", "r") as fields_pull:
    fields_pull = fields_pull.read().splitlines()
NUM_SUBJECTS = len(figures_pull_list)
task_name = 'Seth_MatchPennies_Agent_Exp1'

# Get Subject Data

In [9]:
NUM_STDS = 2
append_dict = {0:'reaction_time_no_sd_off',1:'reaction_time_minus_sd',2:'reaction_time_minus_2sd'}
load_path = r'D:\Subject_Data\Seth_MatchPennies_Agent_Exp1\Subjects_Analyzed\\'
subject = dill.load((open(load_path + f'subject_object_{append_dict[NUM_STDS]}_dict.pkl', 'rb')))
group = dill.load((open(load_path + f'group_object_{append_dict[NUM_STDS]}.pkl', 'rb')))

# Create Model Object

In [10]:
group_model = Optimal_Stopping_Object_v3.Optimal_Decision_Time_Model(reaction_time = group.adjusted_reaction_time_mean, movement_time = group.reaction_movement_time_mean, incorrect_cost = 0,
                                          reaction_uncertainty = group.reaction_time_sd, movement_uncertainty = group.reaction_movement_time_sd,
                                          timing_uncertainty = group.coincidence_reach_time_sd,
                                          decision_action_delay_uncertainty = 10, decision_action_delay_mean = 50,
                                          unknown_gamble_uncertainty_on = False, unknown_gamble_uncertainty = 100,
                                          unknown_gamble_delay_on = True, unknown_gamble_delay = 200,
                                          known_gamble_uncertainty_on = False, known_gamble_uncertainty = 100,
                                          known_gamble_delay_on = False, known_gamble_delay = 200
                                         )
group_model.run_model()

In [11]:
data_wins = np.mean(group.combine_all_subjects('player_perc_wins'),axis=0)
data_wins_tiled = np.tile(data_wins,(2000,1)).T
data_indecisions = np.mean(group.combine_all_subjects('player_perc_indecisions'),axis=0)
data_indecisions_tiled = np.tile(data_indecisions,(2000,1)).T
data_incorrects = np.mean(group.combine_all_subjects('player_perc_incorrects'),axis=0)
data_incorrects_tiled = np.tile(data_incorrects,(2000,1)).T


In [12]:
arr = np.array([0,1,2])
np.

SyntaxError: invalid syntax (3721946851.py, line 2)

In [ ]:
10/np.nan

nan

In [ ]:
x = abs(data_wins_tiled -group_model.prob_win*100)
np.argmin(x,axis=1)

array([1008,  953,  967, 1281, 1177,  964], dtype=int64)

In [ ]:
y = abs(data_indecisions_tiled - group_model.prob_indecision*100)
np.argmin(y,axis=1)

array([1246, 1198, 1146, 1188, 1162, 1178], dtype=int64)

In [ ]:
z = abs(data_incorrects_tiled - group_model.prob_incorrect*100)
np.argmin(z,axis=1)

array([1039, 1077, 1113, 1114, 1140, 1157], dtype=int64)

In [ ]:
timesteps = np.tile(np.arange(500,2000,1),(6,1))


data_compare = np.hstack((data_wins,data_indecisions,data_incorrects))





In [ ]:
data_compare.shape

(18,)

In [ ]:
minimize_function(initial_guess,data_compare)

[1000 1000 1000 1000 1000 1000]


AttributeError: 'Optimal_Decision_Time_Model' object has no attribute 'run_model_fit'

In [ ]:
np.mean(data_wins,axis=0).shape

()

In [ ]:
data_wins

array([[58.75, 70.  , 53.75, 53.75, 42.5 , 55.  ],
       [90.  , 86.25, 53.75, 65.  , 37.5 , 53.75],
       [82.5 , 71.25, 42.5 , 52.5 , 26.25, 66.25],
       [47.5 , 55.  , 43.75, 56.25, 43.75, 45.  ],
       [93.75, 78.75, 73.75, 66.25, 45.  , 68.75],
       [68.75, 58.75, 55.  , 58.75, 42.5 , 55.  ],
       [83.75, 61.25, 62.5 , 50.  ,  6.25, 41.25],
       [68.75, 70.  , 61.25, 66.25, 40.  , 43.75],
       [92.5 , 83.75, 67.5 , 57.5 , 31.25, 50.  ],
       [86.25, 71.25, 53.75, 55.  , 52.5 , 47.5 ],
       [67.5 , 57.5 , 46.25, 48.75, 33.75, 57.5 ],
       [80.  , 67.5 , 60.  , 55.  , 47.5 , 56.25],
       [36.25, 55.  , 20.  , 52.5 , 41.25, 55.  ],
       [81.25, 71.25, 45.  , 65.  , 37.5 , 50.  ],
       [80.  , 63.75, 58.75, 63.75, 38.75, 61.25],
       [83.75, 65.  , 42.5 , 45.  , 47.5 , 46.25],
       [85.  , 81.25, 62.5 , 65.  , 41.25, 55.  ],
       [78.75, 67.5 , 37.5 , 58.75, 35.  , 61.25],
       [91.25, 81.25, 65.  , 66.25, 42.5 , 53.75]])