In [1]:
from Subject_Object_v3 import SubjectBuilder, Group
import numpy as np
import dill
import os
%load_ext autoreload
%autoreload 2

In [2]:
def pickle_subject_objects(subject_list,load_path):
    '''
    Deprecated, generating subject objects is faster than storing the processed objects
    '''
    subject_objects = []
    for i,subname in enumerate(subject_list):
        print(subname)
        subject_object = dill.load(open(load_path + f'\\{subname}\\{subname}_object.pkl', 'rb'))
        subject_objects.append(subject_object)
    return subject_objects

def generate_subject_objects(experiment):
    #* Experiment specific Constants
    if True:
        experiment = experiment

        if experiment == 'Exp1':
            COINCIDENCE_TRIALS = 50
            INTERVAL_TRIALS = 50
            REACTION_TRIALS = 50
            REACTION_BLOCKS = 3
            REACTION_TRIAL_TIME = 5000
            TASK_BLOCKS = 6
            TASK_TRIALS = 80
        elif experiment == 'Exp2':
            COINCIDENCE_TRIALS = 50
            INTERVAL_TRIALS = 50
            REACTION_TRIALS = 100
            REACTION_BLOCKS = 3
            REACTION_TRIAL_TIME = 8000
            TASK_BLOCKS = 4
            TASK_TRIALS = 80
        TIMING_TRIALS = 50
        TRIAL_TIME = 2000
        
    #* Get pull list and num subjects
    if True:
        # Fields pull and pull list
        PATH = f'D:\\OneDrive - University of Delaware - o365\\Subject_Data\\MatchPennies_Agent_{experiment}'
        os.chdir(PATH)
        figures_pull_list = []
        fields_pull = []
        with open(PATH+"\\Figures_Pull_List.txt", "r") as pull_file:
            figures_pull_list = pull_file.read().splitlines()
        with open(PATH+"\\Fields_Pull.txt", "r") as fields_pull:
            fields_pull = fields_pull.read().splitlines()
        NUM_SUBJECTS = len(figures_pull_list)
    
    #* Load control data
    if True:
        # ---------------Controls-------------------------
        reaction_trial_start          = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS, REACTION_TRIALS))*np.nan
        reaction_filenames            = np.empty((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS),dtype = object)
        agent_reaction_leave_time     = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS))*np.nan
        agent_reaction_decision_array = np.empty((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS))*np.nan
        reaction_trial_type_array     = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS))*np.nan
        reaction_xypos_data           = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS, REACTION_TRIAL_TIME,2))*np.nan
        reaction_dist_data            = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS, REACTION_TRIAL_TIME))*np.nan
        reaction_xyvelocity_data      = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS, REACTION_TRIAL_TIME,2))*np.nan
        reaction_speed_data           = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS, REACTION_TRIAL_TIME))*np.nan
        # reaction_xyforce_data         = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS, REACTION_TRIAL_TIME,2))*np.nan
        # reaction_force_data           = np.zeros((NUM_SUBJECTS, REACTION_BLOCKS,REACTION_TRIALS, REACTION_TRIAL_TIME))*np.nan 

        coincidence_trial_start                       = np.zeros((NUM_SUBJECTS, COINCIDENCE_TRIALS))*np.nan
        coincidence_reach_time                        = np.zeros((NUM_SUBJECTS, COINCIDENCE_TRIALS))*np.nan
        interval_trial_start                          = np.zeros((NUM_SUBJECTS, INTERVAL_TRIALS))*np.nan
        interval_reach_time                           = np.zeros((NUM_SUBJECTS, INTERVAL_TRIALS))*np.nan

        for i in range(NUM_SUBJECTS):
            subname = figures_pull_list[i]
            data_path = PATH+f'\\Subjects_Analyzed\\{subname}\\'
            reaction_trial_start[i,...]          = dill.load(open(data_path + f'{subname}_reaction_trial_start.pkl','rb'))          
            reaction_trial_type_array[i,...]          = dill.load(open(data_path + f'{subname}_reaction_trial_type_array.pkl','rb'))          
            # reaction_filenames[i,...]            = dill.load(open(data_path + f'{subname}_reaction_filenames.pkl','rb'))            
            agent_reaction_leave_time[i,...]     = dill.load(open(data_path + f'{subname}_agent_reaction_leave_time.pkl','rb'))  
            agent_reaction_decision_array[i,...] = dill.load(open(data_path + f'{subname}_agent_reaction_decision_array.pkl','rb')) 
            reaction_xypos_data[i,...]           = dill.load(open(data_path + f'{subname}_reaction_xypos_data.pkl','rb'))           
            reaction_dist_data[i,...]            = dill.load(open(data_path + f'{subname}_reaction_dist_data.pkl','rb'))            
            reaction_xyvelocity_data[i,...]      = dill.load(open(data_path + f'{subname}_reaction_xyvelocity_data.pkl','rb'))      
            reaction_speed_data[i,...]           = dill.load(open(data_path + f'{subname}_reaction_speed_data.pkl','rb'))            
            interval_trial_start[i,:]            = dill.load(open(data_path + f'{subname}_interval_trial_start.pkl', 'rb'))
            interval_reach_time[i,:]             = dill.load(open(data_path + f'{subname}_interval_reach_time.pkl', 'rb'))
            coincidence_trial_start[i,:]         = dill.load(open(data_path + f'{subname}_coincidence_trial_start.pkl', 'rb'))
            coincidence_reach_time[i,:]          = dill.load(open(data_path + f'{subname}_coincidence_reach_time.pkl', 'rb'))
    
    #* Load Task Data
    if True:
        # ---------------Controls-------------------------
        task_trial_start          = np.zeros((NUM_SUBJECTS, TASK_BLOCKS, TASK_TRIALS))*np.nan
        task_filenames            = np.empty((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS),dtype = object)
        agent_task_leave_time     = np.zeros((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS))*np.nan
        agent_task_decision_array = np.empty((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS))*np.nan
        task_xypos_data           = np.zeros((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS, TRIAL_TIME,2))*np.nan
        task_dist_data            = np.zeros((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS, TRIAL_TIME))*np.nan
        task_xyvelocity_data      = np.zeros((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS, TRIAL_TIME,2))*np.nan
        task_speed_data           = np.zeros((NUM_SUBJECTS, TASK_BLOCKS,TASK_TRIALS, TRIAL_TIME))*np.nan 
        
        for i in range(NUM_SUBJECTS):
            subname = figures_pull_list[i]
            data_path = PATH+f'\\Subjects_Analyzed\\{subname}\\'
            task_trial_start[i,...]          = dill.load(open(data_path + f'{subname}_task_trial_start.pkl','rb'))                      
            agent_task_leave_time[i,...]     = dill.load(open(data_path + f'{subname}_agent_task_leave_time.pkl','rb'))  
            agent_task_decision_array[i,...] = dill.load(open(data_path + f'{subname}_agent_task_decision_array.pkl','rb')) 
            task_xypos_data[i,...]           = dill.load(open(data_path + f'{subname}_task_xypos_data.pkl','rb'))           
            task_dist_data[i,...]            = dill.load(open(data_path + f'{subname}_task_dist_data.pkl','rb'))            
            task_xyvelocity_data[i,...]      = dill.load(open(data_path + f'{subname}_task_xyvelocity_data.pkl','rb'))      
            task_speed_data[i,...]           = dill.load(open(data_path + f'{subname}_task_speed_data.pkl','rb'))           
            
    #* Generate Subject Objects
    if True:
        data_path = 'Subjects_Analyzed\\'
        subject_objects = []
        for i in range(len(figures_pull_list)):
            subname = figures_pull_list[i]
            print(subname)
            subject_object = SubjectBuilder(
                subject = subname,experiment = experiment, num_task_trials_initial = TASK_TRIALS, num_task_blocks = TASK_BLOCKS, 
                num_reaction_blocks = REACTION_BLOCKS, num_reaction_trials = REACTION_TRIALS,num_timing_trials = TIMING_TRIALS, select_trials='All Trials',
                
                reaction_trial_start = reaction_trial_start[i], reaction_xypos_data = reaction_xypos_data[i],
                reaction_dist_data = reaction_dist_data[i], reaction_xyvelocity_data = reaction_xyvelocity_data[i],
                reaction_speed_data = reaction_speed_data[i], reaction_trial_type_array = reaction_trial_type_array[i], 
                agent_reaction_decision_array = agent_reaction_decision_array[i],agent_reaction_leave_time = agent_reaction_leave_time[i], 
                
                task_xypos_data = task_xypos_data[i], task_dist_data = task_dist_data[i], task_xyvelocity_data = task_xyvelocity_data[i], task_speed_data = task_speed_data[i],
                interval_trial_start = interval_trial_start[i], interval_reach_time = interval_reach_time[i], coincidence_trial_start = coincidence_trial_start[i], coincidence_reach_time = coincidence_reach_time[i],
                agent_task_leave_time = agent_task_leave_time[i], agent_task_decision_array = agent_task_decision_array[i],
                                        )
            subject_objects.append(subject_object)
    assert TRIAL_TIME == 2000    
    return subject_objects

In [3]:
subs = generate_subject_objects(experiment='Exp1')

Sub1
Sub2
Sub3
Sub4
Sub5
Sub6
Sub7
Sub8
Sub9
Sub10
Sub11
Sub12
Sub13
Sub14
Sub15
Sub16
Sub17
Sub18
Sub19
Sub20


In [4]:
subs[0].reaction_gamble_metrics.react_guess_indecisions('guess')

array([30, 10, 24, 33, 43, 21], dtype=int64)

In [5]:
g = Group(subs)

In [24]:
g.get_metric('score_metrics','score_metric',
             'wins')

array([[47., 56., 43., 43., 34., 44.],
       [72., 69., 43., 52., 30., 43.],
       [66., 57., 34., 42., 21., 53.],
       [38., 44., 35., 45., 35., 36.],
       [75., 63., 59., 53., 36., 55.],
       [55., 47., 44., 48., 34., 44.],
       [67., 49., 50., 40.,  5., 34.],
       [55., 56., 49., 53., 32., 35.],
       [74., 67., 54., 46., 25., 40.],
       [69., 57., 43., 44., 42., 38.],
       [54., 46., 37., 39., 27., 46.],
       [64., 54., 48., 44., 38., 45.],
       [29., 44., 16., 42., 33., 44.],
       [65., 57., 36., 52., 30., 40.],
       [64., 51., 47., 51., 31., 49.],
       [67., 52., 34., 36., 38., 38.],
       [68., 65., 50., 52., 33., 44.],
       [63., 55., 30., 47., 28., 50.],
       [73., 65., 52., 53., 34., 43.],
       [46., 40., 38., 41., 35., 52.]])

In [18]:
[getattr(sub_obj, 'score_metric')('indecisions') for sub_obj in g.score_metrics]

[array([ 2, 13, 12,  4,  3, 15], dtype=int64),
 array([ 1,  7, 16, 13, 24, 18], dtype=int64),
 array([ 3,  6, 27,  7, 24,  4], dtype=int64),
 array([ 6,  9,  5, 11,  6, 13], dtype=int64),
 array([ 5,  9, 17, 15, 18,  9], dtype=int64),
 array([ 7,  6,  8, 24, 15,  5], dtype=int64),
 array([13, 24, 28, 36, 55, 35], dtype=int64),
 array([ 2,  8, 18,  6,  9,  6], dtype=int64),
 array([ 4,  8, 22, 27, 34, 27], dtype=int64),
 array([ 3, 19, 26, 17, 11, 15], dtype=int64),
 array([ 3, 19,  9, 17, 23,  6], dtype=int64),
 array([15, 17, 12, 15, 11, 16], dtype=int64),
 array([ 6,  1, 62,  3, 16,  5], dtype=int64),
 array([13, 13, 37, 13, 17, 14], dtype=int64),
 array([ 2,  8,  8,  8, 14,  6], dtype=int64),
 array([10, 21, 15, 30, 14, 15], dtype=int64),
 array([2, 2, 2, 2, 1, 2], dtype=int64),
 array([ 8, 16, 30, 19, 15, 11], dtype=int64),
 array([ 0,  5, 12,  4, 17, 14], dtype=int64),
 array([11,  6, 10, 11,  5,  3], dtype=int64)]

In [17]:
getattr(g.subject_objects[0].score_metrics, 'score_metric')

<bound method ScoreMetrics.score_metric of <Subject_Object_v3.ScoreMetrics object at 0x000002B23AB261A0>>